"""The single shared state object that flows through the graph.

Design notes
------------
* The state is a plain dataclass of JSON-serialisable primitives. That is
  deliberate: it means the whole run can be checkpointed to disk after every
  node, and the QA stage can resume in a *different process* days later.
* Large blobs (full parsed text, embeddings) are NOT kept in the state. The
  state holds *references*: a path to the parsed-text sidecar file and the name
  of the vector-store collection. Keeping the state small keeps checkpointing
  cheap and keeps the state readable when debugging.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any


def new_session_id() -> str:
    return f"s{int(time.time())}-{uuid.uuid4().hex[:6]}"


@dataclass
class PaperMeta:
    """Bibliographic metadata straight from the arXiv Atom feed.

    These fields are *never* generated by the LLM — they come from the API, so
    the briefing header cannot be hallucinated.
    """

    arxiv_id: str = ""
    version: str = ""
    title: str = ""
    authors: list[str] = field(default_factory=list)
    abstract: str = ""
    categories: list[str] = field(default_factory=list)
    primary_category: str = ""
    published: str = ""
    updated: str = ""
    abs_url: str = ""
    pdf_url: str = ""
    comment: str = ""
    doi: str = ""
    journal_ref: str = ""

    def short(self) -> dict[str, Any]:
        return {
            "arxiv_id": self.arxiv_id,
            "title": self.title,
            "published": self.published[:10],
            "primary_category": self.primary_category,
        }


@dataclass
class QueryPlan:
    """Structured form of the user's request, used to build arXiv queries."""

    phrases: list[str] = field(default_factory=list)  # multi-word concepts
    terms: list[str] = field(default_factory=list)  # single keywords
    categories: list[str] = field(default_factory=list)  # e.g. cs.CL
    authors: list[str] = field(default_factory=list)
    since_year: int | None = None
    source: str = "heuristic"  # heuristic | llm


@dataclass
class ParseReport:
    """What happened during PDF extraction — surfaced to the user, not hidden."""

    parser: str = ""
    pages_total: int = 0
    pages_parsed: int = 0
    chars: int = 0
    section_count: int = 0
    reference_count: int = 0
    truncated: bool = False
    degraded: bool = False  # true => briefing built from abstract only
    quality_score: float = 0.0
    warnings: list[str] = field(default_factory=list)


@dataclass
class AgentState:
    # --- identity ---
    session_id: str = field(default_factory=new_session_id)
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)

    # --- stage 1: query understanding ---
    raw_input: str = ""
    intent: str = "unknown"  # paper_lookup | topic_search | unknown
    arxiv_id: str = ""
    query_plan: dict[str, Any] = field(default_factory=dict)

    # --- stage 2: retrieval ---
    query_attempts: list[dict[str, Any]] = field(default_factory=list)
    candidates: list[dict[str, Any]] = field(default_factory=list)

    # --- stage 3: selection ---
    paper: dict[str, Any] | None = None
    selection_rationale: str = ""
    runners_up: list[dict[str, Any]] = field(default_factory=list)
    needs_disambiguation: bool = False

    # --- stage 4: fetch & parse ---
    pdf_path: str = ""
    parsed_path: str = ""  # sidecar JSON with sections + full text
    parse_report: dict[str, Any] = field(default_factory=dict)

    # --- stage 5: chunk & embed ---
    collection: str = ""
    chunk_count: int = 0
    embedder: str = ""
    vector_backend: str = ""

    # --- stage 6: briefing ---
    briefing: dict[str, Any] | None = None
    briefing_md_path: str = ""
    briefing_json_path: str = ""

    # --- stage 7: QA ---
    qa_history: list[dict[str, Any]] = field(default_factory=list)
    pending_question: str = ""

    # --- control plane ---
    status: str = "running"  # running | briefed | failed | no_results | awaiting_user
    halt_reason: str = ""
    errors: list[dict[str, Any]] = field(default_factory=list)
    trace: list[dict[str, Any]] = field(default_factory=list)

    # ------------------------------------------------------------------ #
    def record_error(self, node: str, exc: BaseException, recoverable: bool = True) -> None:
        self.errors.append(
            {
                "node": node,
                "type": type(exc).__name__,
                "message": str(exc)[:500],
                "recoverable": recoverable,
                "ts": time.time(),
            }
        )

    def note(self, node: str, message: str) -> None:
        self.trace.append({"node": node, "note": message, "ts": time.time()})

    @property
    def paper_meta(self) -> PaperMeta:
        return PaperMeta(**(self.paper or {}))

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AgentState":
        known = {f for f in cls.__dataclass_fields__}  # type: ignore[attr-defined]
        return cls(**{k: v for k, v in data.items() if k in known})
